//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigALoan_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHLD_StudentReferences
    {
        public int RefID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public System.DateTimeOffset DateAdded { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual CORE_Students CORE_Students { get; set; }
        public virtual SPRT_GigTypes SPRT_GigTypes { get; set; }
    }
}
