//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigALoan_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHLD_StudentLoans
    {
        public int LoanID { get; set; }
        public int StudentID { get; set; }
        public int CompanyID { get; set; }
        public Nullable<double> LoanAmount { get; set; }
        public string AccountNum { get; set; }
    
        public virtual SPRT_LoanCompanies SPRT_LoanCompanies { get; set; }
        public virtual CORE_Students CORE_Students { get; set; }
    }
}
