//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigALoan_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHLD_ClientImages
    {
        public int ImageID { get; set; }
        public int ClientID { get; set; }
        public string ImageURL { get; set; }
        public string ImageUUID { get; set; }
        public string ImageName { get; set; }
    
        public virtual CORE_Clients CORE_Clients { get; set; }
    }
}
