//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigALoan_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORE_GigAlerts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CORE_GigAlerts()
        {
            this.CORE_Gigs = new HashSet<CORE_Gigs>();
        }
    
        public int AlertID { get; set; }
        public int ClientID { get; set; }
        public int TypeID { get; set; }
        public string Title { get; set; }
        public string Comment { get; set; }
        public double PaymentAmt { get; set; }
        public double Long { get; set; }
        public double Lat { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Active { get; set; }
    
        public virtual CORE_Clients CORE_Clients { get; set; }
        public virtual SPRT_GigTypes SPRT_GigTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CORE_Gigs> CORE_Gigs { get; set; }
    }
}
