//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigALoan_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CORE_Gigs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CORE_Gigs()
        {
            this.CHLD_GigImages = new HashSet<CHLD_GigImages>();
        }
    
        public int GigID { get; set; }
        public int StudentID { get; set; }
        public int AlertID { get; set; }
        public System.DateTime DateAccepted { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<double> StudentRating { get; set; }
        public Nullable<double> ClientRating { get; set; }
        public string StudentComments { get; set; }
        public string ClientComments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHLD_GigImages> CHLD_GigImages { get; set; }
        public virtual CORE_GigAlerts CORE_GigAlerts { get; set; }
        public virtual CORE_Students CORE_Students { get; set; }
    }
}
