//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigALoan_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_Events
    {
        public int LogID { get; set; }
        public Nullable<System.DateTime> DateLogged { get; set; }
        public string LogMessage { get; set; }
    }
}
